#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "ERROR ==> This script must be run as root!"
   exit 1
fi

# Workspace settings
RPIC_OPT_FOLDER=${RPIC_OPT:-"/opt/rpic"}
RPIC_DEPS_FOLDER=${RPIC_OPT_FOLDER}/deps
RPIC_APP_FOLDER=${RPIC_OPT_FOLDER}/app
RPIC_OPT_BACKUP_FOLDER=${RPIC_OPT_FOLDER}/backup
RPIC_WORKSPACE_FOLDER=${RPIC_WORKSPACE:-"/var/rpic"}
RPIC_WORKSPACE_BACKUP_FOLDER=${RPIC_WORKSPACE_FOLDER}/backup
RPIC_WORKSPACE_LOG_FOLDER=${RPIC_WORKSPACE_FOLDER}/logs
RPIC_SYSTEMD_FOLDER=${SYSTEMD_PATH:-"/etc/systemd/system/"}
RPIC_APP_GROUP=${RPIC_GROUP:-"rpic"}

# Application settings
RPIC_APP_DEBUG=${RPIC_DEBUG:-"False"}
RPIC_APP_TIME_ZONE=${RPIC_TIME_ZONE:-"UTC"}
RPIC_APP_LOGGING_LEVEL=${RPIC_LOGGING_LEVEL:-"ERROR"}
RPIC_APP_ENV=${RPIC_ENV:-"PROD"}

# Application external dependencies settings
RPIC_APP_DB_URL=${RPIC_DB_URL}
RPIC_APP_REDIS_CACHE_URL=${RPIC_REDIS_CACHE_URL}
RPIC_APP_CELERY_BROKER_URL=${RPIC_CELERY_BROKER_URL}
RPIC_APP_INFLUXDB=${RPIC_INFLUXDB}
RPIC_APP_SENTRY_DSN=${RPIC_SENTRY_DSN}


# Install system-level dependency
echo "[ Installing system-level dependencies... ]"
apt update
apt install -y python3 python3-dev libgpiod2

# Install uv if needed
echo "[ Checking uv installation... ]"
mkdir -p "${RPIC_DEPS_FOLDER}"
"${RPIC_DEPS_FOLDER}/uv" --version
IS_UV_AVAILABLE=$?
if [ "${IS_UV_AVAILABLE}" != "0" ] ; then
  echo "[ Installing uv... ]"
  curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="${RPIC_DEPS_FOLDER}" sh
  "${RPIC_DEPS_FOLDER}/uv" --version
fi

# Self update uv
echo "[ Upgrading uv... ]"
"${RPIC_DEPS_FOLDER}/uv" self update

# Stop rpic service if available
echo "[ Stopping rpic service... ]"
systemctl stop rpic.target

# Backup opt and var folder
echo "[ Performing application folder backup... ]"
mkdir -p "${RPIC_APP_FOLDER}" "${RPIC_OPT_BACKUP_FOLDER}"
rsync -a --delete "${RPIC_APP_FOLDER}/" "${RPIC_OPT_BACKUP_FOLDER}" || exit 1
echo "[ Performing workspace folder backup... ]"
mkdir -p "${RPIC_WORKSPACE_FOLDER}" "${RPIC_WORKSPACE_BACKUP_FOLDER}" "${RPIC_WORKSPACE_LOG_FOLDER}"
rsync -a --delete "${RPIC_WORKSPACE_FOLDER}/" "${RPIC_WORKSPACE_BACKUP_FOLDER}" --exclude "backup"|| exit 1

# Install app
echo "[ Installing application... ]"
export UV_PROJECT_ENVIRONMENT="${RPIC_APP_FOLDER}/venv"
mkdir -p "${UV_PROJECT_ENVIRONMENT}" "${RPIC_WORKSPACE_FOLDER}/deps/uv-cache"
"${RPIC_DEPS_FOLDER}/uv" sync --cache-dir="${RPIC_WORKSPACE_FOLDER}/deps/uv-cache" --frozen --no-dev --no-editable || exit 1
cp uwsgi.ini "${RPIC_APP_FOLDER}"

if [ -f "${RPIC_OPT_BACKUP_FOLDER}/.env" ] ; then
  echo "[ Restoring required config from .env file backup... ]"
  DJANGO_SECRET_KEY=$(grep SECRET_KEY "${RPIC_OPT_BACKUP_FOLDER}/.env")
  DATABASE_URL=$(grep DATABASE_URL "${RPIC_OPT_BACKUP_FOLDER}/.env")
  DJANGO_SUPERUSER_PASSWORD=$(grep DJANGO_SUPERUSER_PASSWORD "${RPIC_OPT_BACKUP_FOLDER}/.env")
  REDIS_CACHE_URL=$(grep REDIS_CACHE_URL "${RPIC_OPT_BACKUP_FOLDER}/.env")
  CELERY_BROKER_URL=$(grep CELERY_BROKER_URL "${RPIC_OPT_BACKUP_FOLDER}/.env")
  SYSTEM_MONITOR=$(grep SYSTEM_MONITOR "${RPIC_OPT_BACKUP_FOLDER}/.env")
fi

echo "[ Generating required config for .env file... ]"
if [[ "${DJANGO_SECRET_KEY}" == "" ]] ; then
  DJANGO_SECRET_KEY="SECRET_KEY=\"$(${UV_PROJECT_ENVIRONMENT}/bin/django-admin shell -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')\""
fi

if [[ "${DATABASE_URL}" == "" ]] ; then
  if [[ "${RPIC_APP_DB_URL}" == "" ]] ; then
    DATABASE_URL="DATABASE_URL=\"postgres://postgres:postgres@localhost:5432/rpic\""
    echo "WARNING ==>RPIC_APP_DB_URL environment variable is not configured, default value will be used: ${DATABASE_URL}"
  else
    DATABASE_URL="DATABASE_URL=\"${RPIC_APP_DB_URL}\""
  fi
fi

if [[ "${DJANGO_SUPERUSER_PASSWORD}" == "" ]] ; then
    DJANGO_ADMIN_PASSWORD=$(head /dev/urandom | tr -dc 'A-Za-z0-9()*+,-.:<=>?^_{|}' | head -c 13)
    echo " =======> Django Admin password: \"${DJANGO_ADMIN_PASSWORD}\" <==========="
    DJANGO_SUPERUSER_PASSWORD="DJANGO_SUPERUSER_PASSWORD=\"${DJANGO_ADMIN_PASSWORD}\""
fi

if [[ "${REDIS_CACHE_URL}" == "" ]] ; then
  if [[ "${RPIC_APP_REDIS_CACHE_URL}" == "" ]] ; then
    REDIS_CACHE_URL="REDIS_CACHE_URL=\"redis://localhost:6379/1\""
    echo "WARNING ==> RPIC_APP_REDIS_CACHE_URL environment variable is not configured, default value will be used: ${REDIS_CACHE_URL}"
  else
    REDIS_CACHE_URL="REDIS_CACHE_URL=\"${RPIC_APP_REDIS_CACHE_URL}\""
  fi
fi

if [[ "${CELERY_BROKER_URL}" == "" ]] ; then
  if [[ "${RPIC_APP_CELERY_BROKER_URL}" == "" ]] ; then
    CELERY_BROKER_URL="CELERY_BROKER_URL=\"redis://localhost:6379/0\""
    echo "WARNING ==> RPIC_APP_CELERY_BROKER_URL environment variable is not configured, default value will be used: ${CELERY_BROKER_URL}"
  else
    CELERY_BROKER_URL="CELERY_BROKER_URL=\"${RPIC_APP_CELERY_BROKER_URL}\""
  fi
fi

if [[ "${SYSTEM_MONITOR}" == "" ]] ; then
  if [[ "${RPIC_APP_INFLUXDB}" == "" ]] ; then
    SYSTEM_MONITOR="SYSTEM_MONITOR=\"BACKEND=rpi_controller.monitoring.backends.influxdb.InfluxDBv1SystemMonitor;LOCATION=influxdb://root:root@localhost:8086/rpic\""
    echo "WARNING ==> RPIC_APP_INFLUXDB environment variable is not configured, default value will be used: ${RPIC_APP_INFLUXDB}"
  else
    SYSTEM_MONITOR="SYSTEM_MONITOR=\"${RPIC_APP_INFLUXDB}\""
  fi
fi

echo "[ Updating .env file... ]"
  LOGGING_LEVEL=$(grep LOGGING_LEVEL "${RPIC_OPT_BACKUP_FOLDER}/.env")
{
  echo "DJANGO_SETTINGS_MODULE=\"rpi_controller.config.settings\""
  echo "DEBUG=\"${RPIC_APP_DEBUG}\""
  echo "ENVIRONMENT=\"${RPIC_APP_ENV}\""
  echo "TIME_ZONE=\"${RPIC_APP_TIME_ZONE}\""
  echo "LOGGING_LEVEL=\"${RPIC_APP_LOGGING_LEVEL}\""
  echo "SENTRY_DSN=\"${RPIC_APP_SENTRY_DSN}\""
  echo "${DJANGO_SECRET_KEY}"
  echo "ALLOWED_HOSTS=\"*\""
  echo "${DATABASE_URL}"
  echo "DJANGO_SUPERUSER_USERNAME=\"admin\""
  echo "DJANGO_SUPERUSER_EMAIL=\"admin@local.host\""
  echo "${DJANGO_SUPERUSER_PASSWORD}"
  echo "STATIC_URL=\"/static/\""
  echo "STATIC_ROOT=\"${RPIC_WORKSPACE_FOLDER}/static\""
  echo "LOGGING_FILE=\"${RPIC_WORKSPACE_LOG_FOLDER}/rpi_controller.log\""
  echo "${REDIS_CACHE_URL}"
  echo "${CELERY_BROKER_URL}"
  echo "${SYSTEM_MONITOR}"
  echo "C_FORCE_ROOT=\"true\""  # https://docs.celeryq.dev/en/stable/userguide/daemonizing.html#running-the-worker-with-superuser-privileges-root
} > "${RPIC_APP_FOLDER}/.env" || exit 1

echo "[ Loading .env file... ]"
set -o allexport
source "${RPIC_APP_FOLDER}/.env"
set +o allexport

echo "[ Configure application user and group... ]"
groupadd ${RPIC_APP_GROUP}

echo "[ Performing application upgrade... ]"
"${UV_PROJECT_ENVIRONMENT}/bin/django-admin" upgrade --check-deploy || exit 1

echo "[ Configuring systemd service... ]"
{
  echo "[Unit]"
  echo "Description=RPIC service"
  echo "Wants=rpic-webapp.service rpic-celery-worker.service rpic-celery-beat.service"
  echo ""
  echo "[Install]"
  echo "WantedBy=multi-user.target"
} > "${RPIC_SYSTEMD_FOLDER}/rpic.target" || exit 1

{
  echo "[Unit]"
  echo "Description=RPIC web service"
  echo "Requires=rpic.target"
  echo ""
  echo "[Service]"
  echo "WorkingDirectory=${RPIC_WORKSPACE_FOLDER}"
  echo "ExecStart=${UV_PROJECT_ENVIRONMENT}/bin/uwsgi --ini ${RPIC_APP_FOLDER}/uwsgi.ini"
  echo "EnvironmentFile=${RPIC_APP_FOLDER}/.env"
  echo "RuntimeDirectory=uwsgi"
  echo "Restart=always"
  echo "KillSignal=SIGQUIT"
  echo "Type=notify"
  echo "StandardError=syslog"
  echo "NotifyAccess=all"
  echo "Type=simple"
  echo "Group=${RPIC_APP_GROUP}"
  echo ""
  echo "[Install]"
  echo "WantedBy=multi-user.target"
} > "${RPIC_SYSTEMD_FOLDER}/rpic-webapp.service" || exit 1

{
  echo "[Unit]"
  echo "Description=RPIC Celery worker"
  echo "After=network.target redis-server.service"
  echo "Requires=rpic.target"
  echo ""
  echo "[Service]"
  echo "WorkingDirectory=${RPIC_WORKSPACE_FOLDER}"
  echo "ExecStart=${UV_PROJECT_ENVIRONMENT}/bin/celery -A rpi_controller.config.celery multi start worker \\"
  echo "  --pidfile=${RPIC_WORKSPACE_FOLDER}/rpic-celery-worker.pid --logfile=${RPIC_WORKSPACE_LOG_FOLDER}/rpic-worker.log --loglevel=${RPIC_APP_LOGGING_LEVEL}"
  echo "ExecStop=${UV_PROJECT_ENVIRONMENT}/bin/celery -A rpi_controller.config.celery multi stop worker \\"
  echo "  --pidfile=${RPIC_WORKSPACE_FOLDER}/rpic-celery-worker.pid --logfile=${RPIC_WORKSPACE_LOG_FOLDER}/rpic-worker.log --loglevel=${RPIC_APP_LOGGING_LEVEL}"
  echo "ExecReload=${UV_PROJECT_ENVIRONMENT}/bin/celery -A rpi_controller.config.celery multi restart worker \\"
  echo "  --pidfile=${RPIC_WORKSPACE_FOLDER}/rpic-celery-worker.pid --logfile=${RPIC_WORKSPACE_LOG_FOLDER}/rpic-worker.log --loglevel=${RPIC_APP_LOGGING_LEVEL}"
  echo "EnvironmentFile=${RPIC_APP_FOLDER}/.env"
  echo "Restart=always"
  echo "Type=notify"
  echo "StandardError=syslog"
  echo "NotifyAccess=all"
  echo "Type=forking"
  echo "Group=${RPIC_APP_GROUP}"
  echo ""
  echo "[Install]"
  echo "WantedBy=multi-user.target"
} > "${RPIC_SYSTEMD_FOLDER}/rpic-celery-worker.service" || exit 1

{
  echo "[Unit]"
  echo "Description=RPIC Celery beat"
  echo "After=network.target redis-server.service"
  echo "Requires=rpic.target"
  echo ""
  echo "[Service]"
  echo "WorkingDirectory=${RPIC_WORKSPACE_FOLDER}"
  echo "ExecStart=${UV_PROJECT_ENVIRONMENT}/bin/celery -A rpi_controller.config.celery beat \\"
  echo "  --pidfile=${RPIC_WORKSPACE_FOLDER}/rpic-celery-beat.pid --logfile=${RPIC_WORKSPACE_LOG_FOLDER}/rpic-beat.log --loglevel=${RPIC_APP_LOGGING_LEVEL}"
  echo "EnvironmentFile=${RPIC_APP_FOLDER}/.env"
  echo "Restart=always"
  echo "Type=notify"
  echo "StandardError=syslog"
  echo "NotifyAccess=all"
  echo "Type=simple"
  echo "Group=${RPIC_APP_GROUP}"
  echo ""
  echo "[Install]"
  echo "WantedBy=multi-user.target"
} > "${RPIC_SYSTEMD_FOLDER}/rpic-celery-beat.service" || exit 1

systemctl daemon-reload || exit 1

echo "[ Configure workspace permissions... ]"
chown -R root:${RPIC_APP_GROUP} "${RPIC_OPT_FOLDER}" "${RPIC_WORKSPACE_FOLDER}" || exit 1
chmod -R o-rwx "${RPIC_OPT_FOLDER}" "${RPIC_WORKSPACE_FOLDER}" || exit 1
chmod -R g=u "${RPIC_OPT_FOLDER}" "${RPIC_WORKSPACE_FOLDER}" || exit 1

# Start rpic service
echo "[ Starting rpic service... ]"
systemctl enable rpic.target || exit 1
systemctl start rpic.target || exit 1
