#!/bin/bash

RPIC_OPT_FOLDER=${RPIC_OPT:-"/opt/rpic"}
RPIC_DEPS_FOLDER=${RPIC_OPT_FOLDER}/deps
RPIC_APP_FOLDER=${RPIC_OPT_FOLDER}/app
RPIC_OPT_BACKUP_FOLDER=${RPIC_OPT_FOLDER}/backup
RPIC_WORKSPACE_FOLDER=${RPIC_WORKSPACE:-"/var/rpic"}
RPIC_WORKSPACE_BACKUP_FOLDER=${RPIC_WORKSPACE_FOLDER}/backup
RPIC_APP_DEBUG=${RPIC_DEBUG:-"False"}
RPIC_APP_TIME_ZONE=${RPIC_TIME_ZONE:-"UTC"}
SYSTEMD_FOLDER=${SYSTEMD_PATH:-"/etc/systemd/system/"}


# Install system-level dependency
echo "[ Installing system-level dependencies... ]"
apt update
apt install python3 python3-dev pigpiod

# Start pigpiod service
echo "[ Starting pigpiod service... ]"
systemctl enable pigpiod.service || exit 1
systemctl restart pigpiod.service || exit 1

# Install uv if needed
echo "[ Checking uv installation... ]"
mkdir -p "${RPIC_DEPS_FOLDER}"
"${RPIC_DEPS_FOLDER}/uv" --version
IS_UV_AVAILABLE=$?
if [ "${IS_UV_AVAILABLE}" != "0" ] ; then
  echo "[ Installing uv... ]"
  curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="${RPIC_DEPS_FOLDER}" sh
  "${RPIC_DEPS_FOLDER}/uv" --version
fi

# Self update uv
echo "[ Upgrading uv... ]"
"${RPIC_DEPS_FOLDER}/uv" self update

# Stop rpic service if available
echo "[ Stopping rpic service... ]"
systemctl stop rpic.service

# Backup opt and var folder
echo "[ Performing app folder backup... ]"
mkdir -p "${RPIC_APP_FOLDER}" "${RPIC_OPT_BACKUP_FOLDER}"
rsync -a --delete "${RPIC_APP_FOLDER}/" "${RPIC_OPT_BACKUP_FOLDER}" || exit 1
echo "[ Performing workspace folder backup... ]"
mkdir -p "${RPIC_WORKSPACE_FOLDER}" "${RPIC_WORKSPACE_BACKUP_FOLDER}"
rsync -a --delete "${RPIC_WORKSPACE_FOLDER}/" "${RPIC_WORKSPACE_BACKUP_FOLDER}" --exclude "backup"|| exit 1

# Install app
echo "[ Installing application... ]"
export UV_PROJECT_ENVIRONMENT="${RPIC_APP_FOLDER}/venv"
mkdir -p "${UV_PROJECT_ENVIRONMENT}" "${RPIC_WORKSPACE_FOLDER}/deps/uv-cache"
"${RPIC_DEPS_FOLDER}/uv" sync --cache-dir="${RPIC_WORKSPACE_FOLDER}/deps/uv-cache" --frozen --no-dev --no-editable || exit 1
cp uwsgi.ini "${RPIC_APP_FOLDER}"

if [ -f "${RPIC_OPT_BACKUP_FOLDER}/.env" ] ; then
  echo "[ Restoring required config from .env file backup... ]"
  DJANGO_SECRET_KEY=$(grep SECRET_KEY "${RPIC_OPT_BACKUP_FOLDER}/.env")
else
  echo "[ Generating required config for .env file... ]"
  DJANGO_SECRET_KEY="SECRET_KEY=\"$(${UV_PROJECT_ENVIRONMENT}/bin/django-admin shell -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')\""
fi
echo "[ Updating .env file... ]"
{
  echo "DEBUG=\"${RPIC_APP_DEBUG}\"" ;
  echo "TIME_ZONE=\"${RPIC_APP_TIME_ZONE}\"" ;
  echo "${DJANGO_SECRET_KEY}" ;
  echo "ALLOWED_HOSTS=\"*\"" ;
  echo "DATABASE_URL=\"sqlite:///${RPIC_WORKSPACE_FOLDER}/rpi-controller.db\"" ;
  echo "DJANGO_SUPERUSER_USERNAME=\"admin\"" ;
  echo "DJANGO_SUPERUSER_EMAIL=\"admin@local.host\"" ;
  echo "DJANGO_SUPERUSER_PASSWORD=\"Admin123!\"" ;
  echo "STATIC_URL=\"/static/\"" ;
  echo "STATIC_ROOT=\"${RPIC_WORKSPACE_FOLDER}/static\"" ;
  echo "DJANGO_SETTINGS_MODULE=\"rpi_controller.config.settings\"" ;
} > "${RPIC_APP_FOLDER}/.env" || exit 1

echo "[ Loading .env file... ]"
set -o allexport
source "${RPIC_APP_FOLDER}/.env"
set +o allexport

echo "[ Performing application upgrade... ]"
"${UV_PROJECT_ENVIRONMENT}/bin/django-admin" upgrade || exit 1

echo "[ Configuring systemd service... ]"
{
  echo "[Unit]"
  echo "Description=RPIC web service"
  echo ""
  echo "[Service]"
  echo "ExecStart=${UV_PROJECT_ENVIRONMENT}/bin/uwsgi --ini ${RPIC_APP_FOLDER}/uwsgi.ini"
  echo "EnvironmentFile=${RPIC_APP_FOLDER}/.env"
  echo "RuntimeDirectory=uwsgi"
  echo "Restart=always"
  echo "KillSignal=SIGQUIT"
  echo "Type=notify"
  echo "StandardError=syslog"
  echo "NotifyAccess=all"
  echo ""
  echo "[Install]"
  echo "WantedBy=multi-user.target"
} > "${SYSTEMD_FOLDER}/rpic.service" || exit 1
systemctl daemon-reload || exit 1

# Start rpic service
echo "[ Starting rpic service... ]"
systemctl enable rpic.service || exit 1
systemctl start rpic.service || exit 1
