[uwsgi]
master = True
vacuum = True
processes = 2
http = :8000
module = rpi_controller.config.wsgi:application
env = DJANGO_SETTINGS_MODULE=rpi_controller.config.settings
static-map=$(STATIC_URL)=$(STATIC_ROOT)
