# Generated by Django 4.2.16 on 2024-12-13 08:11

from django.db import migrations, models
import strategy_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('interface', strategy_field.fields.StrategyField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
