# Generated by Django 4.2.16 on 2025-02-07 09:51

from django.db import migrations, models
import django.db.models.deletion
import strategy_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('visible', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('status', models.JSONField(default=dict, help_text='The current status of the device')),
                ('last_update_status', models.CharField(choices=[('NW', 'NEW'), ('SC', 'SUCCESS'), ('FA', 'FAILURE')], default='NW', max_length=2)),
                ('last_status_update', models.DateTimeField(blank=True, null=True)),
                ('last_status_update_log', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rpi_controller.device')),
                ('interface', strategy_field.fields.StrategyField()),
            ],
            bases=('rpi_controller.device',),
        ),
    ]
