# Generated by Django 4.2.16 on 2025-01-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpi_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_status_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
