# Generated by Django 4.2.16 on 2025-02-07 15:44

from django.db import migrations, models
import django.db.models.deletion
import strategy_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpi_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rpi_controller.device')),
                ('interface', strategy_field.fields.StrategyField()),
            ],
            bases=('rpi_controller.device',),
        ),
    ]
