# Generated by Django 4.2.16 on 2025-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpi_controller', '0002_sensor_last_status_updated_sensor_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='last_status_updated',
            new_name='last_status_update',
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_status_update_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_update_status',
            field=models.CharField(choices=[('NW', 'New'), ('SC', 'Success'), ('FA', 'Failure')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.JSONField(default=dict, help_text='The current status of the device'),
        ),
    ]
