# Generated by Django 4.2.16 on 2025-01-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpi_controller', '0003_rename_last_status_updated_sensor_last_status_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_update_status',
            field=models.CharField(choices=[('NW', 'NEW'), ('SC', 'SUCCESS'), ('FA', 'FAILURE')], default='NW', max_length=2),
        ),
    ]
