# Generated by Django 4.2.16 on 2025-02-19 08:43

from django.db import migrations, models
import strategy_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpi_controller', '0004_alter_sensor_last_update_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('visible', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('status', models.JSONField(default=dict, help_text='The current status of the device')),
                ('last_update_status', models.CharField(choices=[('NW', 'NEW'), ('SC', 'SUCCESS'), ('FA', 'FAILURE')], default='NW', max_length=2)),
                ('last_status_update', models.DateTimeField(blank=True, null=True)),
                ('last_status_update_log', models.TextField(blank=True, null=True)),
                ('interface', strategy_field.fields.StrategyField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
