# Generated by Django 4.2.16 on 2025-02-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpi_controller', '0005_actuator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuator',
            old_name='last_status_update',
            new_name='last_status_update_time',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='last_status_update',
            new_name='last_status_update_time',
        ),
    ]
