# Generated by Django 4.2.16 on 2025-04-03 05:46

from django.db import migrations, models
import django.db.models.deletion
import strategy_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpi_controller', '0006_rename_last_status_update_actuator_last_status_update_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledActuatorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpi_controller.actuator')),
            ],
        ),
        migrations.CreateModel(
            name='ControlledSensorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpi_controller.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('visible', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('status', models.JSONField(default=dict, help_text='The current status of the device')),
                ('last_update_status', models.CharField(choices=[('NW', 'NEW'), ('SC', 'SUCCESS'), ('FA', 'FAILURE')], default='NW', max_length=2)),
                ('last_status_update_time', models.DateTimeField(blank=True, null=True)),
                ('last_status_update_log', models.TextField(blank=True, null=True)),
                ('interface', strategy_field.fields.StrategyField()),
                ('actuators', models.ManyToManyField(related_name='controllers', through='rpi_controller.ControlledActuatorDetails', to='rpi_controller.actuator')),
                ('sensors', models.ManyToManyField(related_name='controllers', through='rpi_controller.ControlledSensorDetails', to='rpi_controller.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='controlledsensordetails',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpi_controller.controller'),
        ),
        migrations.AddField(
            model_name='controlledactuatordetails',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpi_controller.controller'),
        ),
    ]
