# Generated by Django 4.2.16 on 2025-05-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('rpi_controller', '0007_controlledactuatordetails_controlledsensordetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='periodic_tasks',
            field=models.ManyToManyField(blank=True, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='controller',
            name='periodic_tasks',
            field=models.ManyToManyField(blank=True, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='periodic_tasks',
            field=models.ManyToManyField(blank=True, to='django_celery_beat.periodictask'),
        ),
    ]
